# Basalt OS branding: logos, icons, boot splash, GRUB theme, console and
# wallpapers. Replaces fedora-logos the same way generic-logos does: it
# provides system-logos and conflicts with the other providers.
#
# Source0 is a tarball of tree/ (scripts/build-rpms.sh makes it): the exact
# filesystem layout, copied into the buildroot unchanged. The artwork in tree/
# is generated by the Basalt OS branding kit; this directory carries its output.
# GRUB integration (Source1, Source2) is for a traditional install, where
# grub2-mkconfig writes /boot/grub2/grub.cfg from /etc/grub.d.

Name:           basalt-logos
Version:        0.1.0
Release:        2%{?dist}
Summary:        Basalt OS logos and icons
License:        CC-BY-SA-4.0
URL:            https://github.com/basalt-os/basalt-os
Source0:        %{name}-%{version}.tar.gz
Source1:        basalt-theme.cfg
Source2:        06_basalt_theme
BuildArch:      noarch

Provides:       system-logos = %{version}-%{release}
Conflicts:      fedora-logos
Conflicts:      generic-logos

%description
Basalt OS logos, icons and pixmaps: the Basalt mark and the "Basalt OS"
lockups, the basalt-logo-icon icon named by LOGO= in os-release (with the
generic system-logo-icon alias), console artwork for /etc/issue, a
fastfetch logo and default configuration, and Cockpit login branding.

%package httpd
Summary:        Basalt OS "powered by" image used by web servers
Provides:       system-logos-httpd = %{version}-%{release}
Provides:       system-logos(httpd-logo-ng)
Conflicts:      fedora-logos-httpd
Conflicts:      generic-logos-httpd

%description httpd
The /usr/share/pixmaps/poweredby.png badge shown by the default web server
test pages, with the Basalt OS mark.

%package -n plymouth-theme-basalt
Summary:        Basalt OS boot splash theme for Plymouth
Requires:       plymouth-plugin-script
Requires:       plymouth-plugin-label
Requires:       plymouth-scripts
Requires(postun): plymouth-scripts

%description -n plymouth-theme-basalt
Boot splash with the Basalt mark on a dark background, a thin progress line
and a readable passphrase prompt for encrypted disks. Ships assets for
standard and HiDPI screens. Select it with plymouth-set-default-theme basalt
and rebuild the initramfs.

%package -n basalt-grub2-theme
Summary:        Basalt OS theme for the GRUB boot menu
%{?systemd_requires}

%description -n basalt-grub2-theme
GRUB theme (background, mark, menu and fonts) and the /etc/grub.d hook that
enables it in grub.cfg (applied at the next grub2-mkconfig run). Because GRUB
reads its files before the encrypted root is unlocked, the theme is copied
from /usr/share/basalt/grub2 to /boot/grub2/themes on install and by
basalt-grub-theme.service at boot when the package version changed.

%package -n basalt-backgrounds
Summary:        Basalt OS desktop wallpapers

%description -n basalt-backgrounds
Light and dark Basalt wallpapers (3840x2160 and 1920x1080) and the GNOME
background description that pairs them.

%package compat
Summary:        Basalt artwork under file names other packages hardcode
Requires:       %{name} = %{version}-%{release}

%description compat
Symbolic links that point legacy file names (fedora-logo-icon, start-here,
fedora-logo*.png, fedora-gdm-logo.png and the spinner watermark) at the
Basalt OS artwork, for software that hardcodes those paths. Mirrors the file
names generic-logos keeps. Not needed on the server image.

%prep
%autosetup -c -n %{name}-%{version}

%build
# Nothing to build: the artwork is generated by brand/basalt-os/src/build.py.

%install
cp -a tree/. %{buildroot}/
install -Dpm 0644 %{SOURCE1} %{buildroot}%{_datadir}/basalt/grub2/basalt-theme.cfg
install -Dpm 0755 %{SOURCE2} %{buildroot}%{_sysconfdir}/grub.d/06_basalt_theme
# Version stamp: basalt-grub-theme-sync copies the theme to /boot only when it changes.
echo '%{version}-%{release}' > %{buildroot}%{_datadir}/basalt/grub2/themes/basalt/.basalt-version

%post -n basalt-grub2-theme
%systemd_post basalt-grub-theme.service
# Put the theme on /boot now; GRUB uses it after the next grub2-mkconfig.
if [ -d /boot/grub2 ]; then
    %{_libexecdir}/basalt/basalt-grub-theme-sync >/dev/null 2>&1 || :
fi

%preun -n basalt-grub2-theme
%systemd_preun basalt-grub-theme.service

%postun -n basalt-grub2-theme
%systemd_postun basalt-grub-theme.service

%postun -n plymouth-theme-basalt
if [ $1 -eq 0 ]; then
    if [ "$(%{_bindir}/plymouth-set-default-theme)" = "basalt" ]; then
        %{_bindir}/plymouth-set-default-theme --reset || :
    fi
fi

%files
%license %{_datadir}/licenses/%{name}/COPYING
%{_datadir}/icons/hicolor/*/apps/basalt-logo-icon.*
%{_datadir}/icons/hicolor/*/apps/basalt-logo.*
%{_datadir}/icons/hicolor/*/apps/system-logo-icon.*
%{_datadir}/pixmaps/basalt-*
%{_datadir}/pixmaps/system-logo-white.*
%dir %{_datadir}/basalt
%{_datadir}/basalt/logos/
%{_datadir}/basalt/console/
%{_datadir}/basalt/fastfetch/
%dir %{_sysconfdir}/xdg/fastfetch
%config(noreplace) %{_sysconfdir}/xdg/fastfetch/config.jsonc
%dir %{_datadir}/cockpit
%dir %{_datadir}/cockpit/branding
%{_datadir}/cockpit/branding/basalt/

%files httpd
%{_datadir}/pixmaps/poweredby.png

%files -n plymouth-theme-basalt
%license %{_datadir}/licenses/%{name}/COPYING
%{_datadir}/plymouth/themes/basalt/

%files -n basalt-grub2-theme
%license %{_datadir}/licenses/%{name}/COPYING
%dir %{_datadir}/basalt
%dir %{_datadir}/basalt/grub2
%dir %{_datadir}/basalt/grub2/themes
%{_datadir}/basalt/grub2/themes/basalt/
%{_datadir}/basalt/grub2/basalt-theme.cfg
%{_sysconfdir}/grub.d/06_basalt_theme
%dir %{_libexecdir}/basalt
%{_libexecdir}/basalt/basalt-grub-theme-sync
%{_unitdir}/basalt-grub-theme.service
%{_presetdir}/85-basalt-grub2-theme.preset

%files -n basalt-backgrounds
%license %{_datadir}/licenses/%{name}/COPYING
%dir %{_datadir}/backgrounds
%{_datadir}/backgrounds/basalt/
%dir %{_datadir}/gnome-background-properties
%{_datadir}/gnome-background-properties/basalt.xml

%files compat
%{_datadir}/icons/hicolor/*/apps/fedora-logo-icon.*
%{_datadir}/icons/hicolor/*/places/start-here.*
%{_datadir}/pixmaps/fedora-logo.png
%{_datadir}/pixmaps/fedora-logo-small.png
%{_datadir}/pixmaps/fedora-logo-sprite.svg
%{_datadir}/pixmaps/fedora-logo-sprite.png
%{_datadir}/pixmaps/fedora-gdm-logo.png
%dir %{_datadir}/plymouth
%dir %{_datadir}/plymouth/themes
%dir %{_datadir}/plymouth/themes/spinner
%{_datadir}/plymouth/themes/spinner/watermark.png

%changelog
* Sat Oct 03 2026 Basalt OS project <noreply@basalt-os.org> - 0.1.0-2
- GRUB theme for traditional installs: /etc/grub.d/06_basalt_theme instead of
  the bootupd static configuration snippet; theme copied to /boot on install.

* Sat Oct 03 2026 Basalt OS project <noreply@basalt-os.org> - 0.1.0-1
- First branding package: logos, icons, Plymouth and GRUB themes, console
  artwork, wallpapers.
