#!/usr/bin/env bash
# Static checks for CI and for local use.
#
#   scripts/ci/lint.sh              run the checks here (needs ShellCheck, rpmlint,
#                                   pykickstart, python3, make; actionlint optional)
#   scripts/ci/lint.sh --container  run them in a throwaway Fedora container that
#                                   has the tools (what CI does)
#
# Checks: `make lint` (shell and Python syntax, ShellCheck, ksvalidator),
# ShellCheck on the CI scripts, rpmlint on every package spec (filters in
# scripts/ci/rpmlint.toml), ksvalidator on the kickstart for this Fedora
# release, actionlint on the workflows.
source "$(dirname "$0")/../lib.sh"

# actionlint, pinned by version and SHA-256 of the release archive.
ACTIONLINT_VERSION=1.7.12
ACTIONLINT_SHA256=8aca8db96f1b94770f1b0d72b6dddcb1ebb8123cb3712530b08cc387b349a3d8

if [[ "${1:-}" == --container ]]; then
  log "running the checks in $FEDORA_IMAGE"
  in_fedora -v "$REPO_ROOT:/src:ro" -w /src \
    -e FEDORA_RELEASE="$FEDORA_RELEASE" -e ACTIONLINT_VERSION="$ACTIONLINT_VERSION" -e ACTIONLINT_SHA256="$ACTIONLINT_SHA256" \
    "$FEDORA_IMAGE" bash -euc '
      dnf -q -y install make ShellCheck rpmlint pykickstart python3 tar gzip >/dev/null 2>&1 ||
        { echo "dnf install failed" >&2; exit 1; }
      tmp=$(mktemp -d)
      url="https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz"
      if curl -fsSL -o "$tmp/a.tgz" "$url" && echo "$ACTIONLINT_SHA256  $tmp/a.tgz" | sha256sum -c --quiet -; then
        tar -xzf "$tmp/a.tgz" -C /usr/local/bin actionlint
      else
        echo "actionlint download or checksum failed" >&2; exit 1
      fi
      # The tree is mounted read-only: work on a copy so make lint can clean up.
      cp -a /src /tmp/src && cd /tmp/src && scripts/ci/lint.sh'
  exit $?
fi

cd "$REPO_ROOT" || die "cannot enter $REPO_ROOT"
fail=0
step() { printf '\n--- %s\n' "$*" >&2; }

step "make lint (syntax, ShellCheck, ksvalidator)"
make --no-print-directory lint || fail=1

step "ShellCheck: CI scripts, basalt-assistant build and lab scripts"
shellcheck -x -S warning scripts/ci/*.sh packages/basalt-assistant/build.sh scripts/lab/assistant-*.sh || fail=1

step "ksvalidator: kickstart (F$FEDORA_RELEASE syntax)"
# The %include files are generated by %pre at install time; they are not
# followed here (no -i), only the kickstart itself is validated.
ksvalidator -v "F$FEDORA_RELEASE" kickstart/basalt-server.ks || fail=1

step "rpmlint: package specs"
mapfile -t specs < <(find packages -name '*.spec' -not -path 'packages/lab/*' | sort)
rpmlint -c scripts/ci/rpmlint.toml "${specs[@]}" || fail=1

if command -v actionlint >/dev/null; then
  step "actionlint: workflows"
  actionlint -no-color .github/workflows/*.yml || fail=1
else
  log "actionlint not installed, workflows not checked"
fi

[[ $fail == 0 ]] || die "lint failed"
log "all checks passed"
