// Command nvidia-gpus writes the assistant's table of NVIDIA GPUs
// (internal/drivers/nvidia-gpus.json) from the supported-gpus.json of an
// NVIDIA Linux driver package, for the version the basalt-nonfree
// repository ships (packages/nvidia/source.conf):
//
//	sh NVIDIA-Linux-x86_64-VERSION.run --extract-only --target run
//	go run ./tools/nvidia-gpus -version VERSION -in run/supported-gpus/supported-gpus.json \
//	  -out internal/drivers/nvidia-gpus.json
//
// The table keeps, per PCI device id, the GPU's name and which driver
// supports it: "" for this version with the open kernel modules, a legacy
// branch ("580", "470", ...) otherwise, or "closed" for a GPU this version
// supports only with the proprietary kernel module. It is an altered copy
// of NVIDIA's file (zlib license, kept in nvidia-gpus.LICENSE).
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

type chip struct {
	DevID    string   `json:"devid"`
	SubDevID string   `json:"subdevid"`
	Name     string   `json:"name"`
	Legacy   string   `json:"legacybranch"`
	Features []string `json:"features"`
}

// Table is the file the assistant embeds.
type Table struct {
	Driver string               `json:"driver"`
	Source string               `json:"source"`
	GPUs   map[string][2]string `json:"gpus"` // device id (4 lower-case hex digits) -> name, branch
}

func main() {
	in := flag.String("in", "", "supported-gpus.json of the driver package")
	out := flag.String("out", "", "output file")
	version := flag.String("version", "", "driver version")
	flag.Parse()
	if *in == "" || *out == "" || *version == "" {
		flag.Usage()
		os.Exit(2)
	}
	b, err := os.ReadFile(*in)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	var src struct {
		Chips []chip `json:"chips"`
	}
	if err := json.Unmarshal(b, &src); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	t := Table{Driver: *version, GPUs: map[string][2]string{},
		Source: "Altered copy of supported-gpus.json from the NVIDIA Linux driver " + *version +
			" (Copyright (c) 2020 NVIDIA Corporation, zlib license, see nvidia-gpus.LICENSE): reduced to the PCI device id, " +
			"the name and the supporting driver branch; generated by tools/nvidia-gpus."}
	// Entries without a subsystem id name the chip; keep the first of
	// those, else the first entry seen.
	sort.SliceStable(src.Chips, func(i, j int) bool { return src.Chips[i].SubDevID == "" && src.Chips[j].SubDevID != "" })
	for _, c := range src.Chips {
		id := strings.ToLower(strings.TrimPrefix(c.DevID, "0x"))
		if len(id) != 4 {
			continue
		}
		if _, ok := t.GPUs[id]; ok {
			continue
		}
		branch := ""
		if c.Legacy != "" {
			branch = strings.TrimSuffix(c.Legacy, ".xx")
		} else {
			open := false
			for _, f := range c.Features {
				open = open || f == "kernelopen"
			}
			if !open {
				branch = "closed"
			}
		}
		t.GPUs[id] = [2]string{c.Name, branch}
	}
	j, err := json.MarshalIndent(t, "", " ")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, append(j, '\n'), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("%d GPUs written to %s\n", len(t.GPUs), *out)
}
