# Basalt OS server image, built on the Fedora bootc base image.
#
#   make build                      # see README.md
#   podman build --network=host --build-arg BASALT_VERSION=0.0.1 -t basalt-os .
#
# build/site/ holds the per-deployment overlay generated by
# scripts/site-overlay.sh (image signature policy and, for a lab registry, its
# CA). It may be empty; it must exist.

ARG BASE_IMAGE=quay.io/fedora/fedora-bootc:44
FROM ${BASE_IMAGE}

ARG BASALT_VERSION=0.0.1
ARG SOURCE_URL=https://github.com/basalt-os/basalt-os

LABEL org.opencontainers.image.title="Basalt OS" \
      org.opencontainers.image.description="Basalt OS server image (pre-alpha), based on Fedora. Not affiliated with the Fedora Project." \
      org.opencontainers.image.version="${BASALT_VERSION}" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.source="${SOURCE_URL}" \
      org.opencontainers.image.vendor="Basalt OS project" \
      containers.bootc="1" \
      ostree.bootable="1"

# Static files: SSH baseline, bootc install defaults, kernel arguments, logo,
# tui-tools repository and its signing key.
COPY rootfs/ /

# Per-deployment overlay (signature policy, registry trust). Generated, not committed.
COPY build/site/ /

RUN --mount=type=bind,source=image,target=/ctx/image,relabel=shared \
    --mount=type=bind,source=packages,target=/ctx/packages,relabel=shared \
    --mount=type=bind,source=selinux,target=/ctx/selinux,relabel=shared \
    BASALT_VERSION="${BASALT_VERSION}" /ctx/image/build.sh

RUN bootc container lint
