# Basalt OS server kickstart (Fedora 44 base, Anaconda).
#
# Embedded into the Fedora netinst ISO by scripts/iso.sh (mkksiso). Installs a
# minimal server from the Fedora mirrors plus the Basalt OS packages, which
# travel on the ISO itself (/basalt on the media).
#
# Boot loader, storage, packages, encryption, accounts and the end of the
# install are generated in %pre from two optional sources:
#   - kernel arguments (edit the boot entry):
#       basalt.encrypt=0      plain btrfs, no LUKS2 (default: 1, encrypted)
#       basalt.disk=vda       target disk (default: the first fixed disk)
#       basalt.finish=poweroff|reboot   (default: reboot)
#       basalt.profile=auto|minimal|standard
#                             auto (default): minimal on a virtual machine,
#                             standard on bare metal (systemd-detect-virt).
#                             minimal: no hardware firmware, CPU microcode or
#                             fwupd. standard: all of them. A VM with
#                             passthrough hardware that needs firmware (GPU,
#                             NIC) wants basalt.profile=standard.
#       basalt.unlock=tpm2|tang|tpm2+tang
#                             how the encrypted disk unlocks at boot (default: tpm2):
#                               tpm2       the TPM, sealed to PCR 7 (Secure Boot state)
#                               tang       a Tang server on the network (Clevis)
#                               tpm2+tang  both: this machine's TPM and the network
#       basalt.tang=URL       Tang server, for tang and tpm2+tang
#       basalt.tang-thp=THP   its signing key thumbprint (tang-show-keys); without
#                             it the first advertisement is trusted and logged
#       basalt.lockdown=0     leave lockdown=integrity and module.sig_enforce=1 off
#                             the kernel command line (default: 1, on)
#   - a site file on the media, /basalt/site.conf (same names, shell syntax:
#     BASALT_ENCRYPT, BASALT_DISK, BASALT_FINISH, BASALT_PROFILE, BASALT_UNLOCK,
#     BASALT_TANG_URL, BASALT_TANG_THP, BASALT_LOCKDOWN, BASALT_SHOW_RECOVERY_KEY,
#     BASALT_RECOVERY_KEY_PAUSE, BASALT_REPO_URL) and /basalt/site.ks (accounts:
#     sshkey, user, rootpw). Without site.ks the installer asks for a root
#     password or a user.
#
# Layout (ADR "update model"): GPT, ESP, /boot (ext4), and one btrfs file
# system, on LUKS2 unless disabled, with these subvolumes:
#   root            /                   the system; snapshots and rollback apply here
#   home            /home               user data, never rolled back
#   srv             /srv                served data
#   var_log         /var/log            logs survive a rollback (and explain it)
#   var_cache       /var/cache          caches, not worth snapshotting
#   var_tmp         /var/tmp
#   var_spool       /var/spool          mail and print queues
#   var_lib_containers  /var/lib/containers   container images and volumes
#   var_lib_libvirt     /var/lib/libvirt      virtual machines
#   var_lib_pgsql       /var/lib/pgsql        PostgreSQL
#   var_lib_mysql       /var/lib/mysql        MariaDB / MySQL
#   root/.snapshots /.snapshots         snapper (created by basalt-snapshots-setup)
# /opt stays in the root: packages install there too, and it must roll back
# with the package database. The rest of /var/lib (SELinux policy store,
# alternatives, systemd state) also stays with the root for the same reason.
# compress=zstd:1 is Anaconda's default for btrfs on Fedora and is active
# while the system is written.

text
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --utc
network --bootproto=dhcp --device=link --activate --onboot=on --hostname=basalt
selinux --enforcing
# The firewall comes from basalt-release-server (zone "basalt", SSH only).
firewall --use-system-defaults
# basalt-assistantd only diagnoses and proposes; applying a change always
# needs `basalt apply` and a confirmation. basalt-notify exits at once on a
# server without a desktop or a webhook configured.
services --enabled=sshd,firewalld,auditd,basalt-snapshot-boot,basalt-initial-snapshot,basalt-grub-theme,basalt-module-keys,basalt-assistantd,basalt-notify,basalt-audit-rotate.timer
skipx
firstboot --disable

# Fedora package repositories ($releasever is the installer's release).
url --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-$releasever&arch=$basearch"
repo --name=updates --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=updates-released-f$releasever&arch=$basearch"

# Generated by %pre: Basalt repository, boot loader, storage, packages,
# accounts, end action.
%include /tmp/basalt-repo.ks
%include /tmp/basalt-boot.ks
%include /tmp/basalt-storage.ks
%include /tmp/basalt-packages.ks
%include /tmp/basalt-site.ks
%include /tmp/basalt-finish.ks

%pre --log=/tmp/basalt-pre.log
#!/bin/bash
set -eu
media=/run/install/repo/basalt
BASALT_ENCRYPT=1
BASALT_DISK=
BASALT_FINISH=reboot
BASALT_SHOW_RECOVERY_KEY=1
BASALT_RECOVERY_KEY_PAUSE=30
BASALT_REPO_URL=
BASALT_PROFILE=auto
BASALT_UNLOCK=tpm2
BASALT_TANG_URL=
BASALT_TANG_THP=
BASALT_LOCKDOWN=1
if [ -r "$media/site.conf" ]; then . "$media/site.conf"; fi
for arg in $(cat /proc/cmdline); do
  case "$arg" in
    basalt.encrypt=*) BASALT_ENCRYPT="${arg#*=}" ;;
    basalt.disk=*) BASALT_DISK="${arg#*=}" ;;
    basalt.finish=*) BASALT_FINISH="${arg#*=}" ;;
    basalt.profile=*) BASALT_PROFILE="${arg#*=}" ;;
    basalt.unlock=*) BASALT_UNLOCK="${arg#*=}" ;;
    basalt.tang=*) BASALT_TANG_URL="${arg#*=}" ;;
    basalt.tang-thp=*) BASALT_TANG_THP="${arg#*=}" ;;
    basalt.lockdown=*) BASALT_LOCKDOWN="${arg#*=}" ;;
  esac
done
case "$BASALT_PROFILE" in auto|standard|minimal) ;; *) echo "unknown basalt.profile=$BASALT_PROFILE" >&2; exit 1 ;; esac
# auto: virtual machines and cloud instances get the minimal profile (no
# hardware firmware), bare metal the standard one.
profile_from="$BASALT_PROFILE"
if [ "$BASALT_PROFILE" = auto ]; then
  virt="$(systemd-detect-virt --vm 2>/dev/null || :)"
  if [ -z "$virt" ] && grep -qw hypervisor /proc/cpuinfo 2>/dev/null; then virt=hypervisor; fi
  if [ -n "$virt" ] && [ "$virt" != none ]; then
    BASALT_PROFILE=minimal; profile_from="auto, virtual machine: $virt"
  else
    BASALT_PROFILE=standard; profile_from="auto, bare metal"
  fi
fi
case "$BASALT_UNLOCK" in tpm2|tang|tpm2+tang) ;; *) echo "unknown basalt.unlock=$BASALT_UNLOCK" >&2; exit 1 ;; esac
network_unlock=0
if [ "$BASALT_ENCRYPT" = 1 ] && [ "$BASALT_UNLOCK" != tpm2 ]; then
  network_unlock=1
  [ -n "$BASALT_TANG_URL" ] || { echo "basalt.unlock=$BASALT_UNLOCK needs basalt.tang=URL" >&2; exit 1; }
fi

# Basalt OS packages: from the media when present, else from BASALT_REPO_URL.
if [ -d "$media/repo" ]; then
  echo "repo --name=basalt --baseurl=file://$media/repo/\$releasever/\$basearch/" >/tmp/basalt-repo.ks
elif [ -n "$BASALT_REPO_URL" ]; then
  echo "repo --name=basalt --baseurl=$BASALT_REPO_URL/\$releasever/\$basearch/" >/tmp/basalt-repo.ks
else
  echo "Basalt OS packages not found on the media and BASALT_REPO_URL is not set" >&2
  exit 1
fi

# Boot loader: serial console first (and the screen); kernel lockdown and
# module signature enforcement, which Fedora kernels apply under Secure Boot
# anyway and which this keeps on when Secure Boot is off; network in the
# initramfs when the disk unlocks through Tang.
append="console=tty0 console=ttyS0,115200n8"
if [ "$BASALT_LOCKDOWN" = 1 ]; then append="$append lockdown=integrity module.sig_enforce=1"; fi
if [ "$network_unlock" = 1 ]; then append="$append rd.neednet=1"; fi
echo "bootloader --timeout=5 --append=\"$append\"" >/tmp/basalt-boot.ks

# Target disk: the first fixed, writable disk unless one is given.
if [ -z "$BASALT_DISK" ]; then
  BASALT_DISK="$(lsblk -dnpo NAME,TYPE,RM,RO | awk '$2 == "disk" && $3 == 0 && $4 == 0 && $1 !~ /\/(zram|loop|nbd|ram)[0-9]/ {print $1; exit}')"
fi
BASALT_DISK="${BASALT_DISK#/dev/}"
[ -n "$BASALT_DISK" ] || { echo "no target disk" >&2; exit 1; }

luks=""
if [ "$BASALT_ENCRYPT" = 1 ]; then
  # A random passphrase that only lives in the installer's memory. %post
  # adds the unlock method and the recovery key, then removes this passphrase.
  umask 077
  tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48 >/tmp/basalt-luks.pass
  luks="--encrypted --luks-version=luks2 --passphrase=$(cat /tmp/basalt-luks.pass)"
fi

cat >/tmp/basalt-storage.ks <<EOF
ignoredisk --only-use=$BASALT_DISK
zerombr
clearpart --all --initlabel --drives=$BASALT_DISK --disklabel=gpt
part /boot/efi --fstype=efi --size=600 --ondisk=$BASALT_DISK
part /boot --fstype=ext4 --size=1024 --ondisk=$BASALT_DISK
part btrfs.basalt --size=8192 --grow --ondisk=$BASALT_DISK $luks
btrfs none --label=basalt btrfs.basalt
btrfs / --subvol --name=root LABEL=basalt
btrfs /home --subvol --name=home LABEL=basalt
btrfs /srv --subvol --name=srv LABEL=basalt
btrfs /var/log --subvol --name=var_log LABEL=basalt
btrfs /var/cache --subvol --name=var_cache LABEL=basalt
btrfs /var/tmp --subvol --name=var_tmp LABEL=basalt
btrfs /var/spool --subvol --name=var_spool LABEL=basalt
btrfs /var/lib/containers --subvol --name=var_lib_containers LABEL=basalt
btrfs /var/lib/libvirt --subvol --name=var_lib_libvirt LABEL=basalt
btrfs /var/lib/pgsql --subvol --name=var_lib_pgsql LABEL=basalt
btrfs /var/lib/mysql --subvol --name=var_lib_mysql LABEL=basalt
EOF

# Packages. The minimal profile leaves out hardware firmware, CPU microcode
# and firmware update tools (fwupd and what it pulls in), which a virtual
# machine does not use; kernel-core only recommends linux-firmware.
{
  echo "%packages"
  cat <<'PKG'
@core
basalt-release
basalt-release-server
basalt-logos
basalt-logos-httpd
basalt-grub2-theme
plymouth-theme-basalt
basalt-snapshots
basalt-security
basalt-assistant
basalt-assistant-selinux
-fedora-release
-fedora-release-common
-fedora-release-identity-basic
-fedora-logos
-fedora-logos-httpd
-generic-release
-generic-logos
btrfs-progs
cryptsetup
tpm2-tss
tpm2-tools
mokutil
keyutils
efibootmgr
audit
policycoreutils-python-utils
setools-console
compsize
glibc-langpack-en
snapper
libdnf5-plugin-actions
PKG
  if [ "$network_unlock" = 1 ]; then
    printf '%s\n' clevis clevis-luks clevis-dracut
  fi
  if [ "$BASALT_PROFILE" = minimal ]; then
    printf '%s\n' -linux-firmware -linux-firmware-whence '-*-firmware' -microcode_ctl '-fwupd*' -flashrom
  fi
  echo "%end"
} >/tmp/basalt-packages.ks

if [ -r "$media/site.ks" ]; then cp "$media/site.ks" /tmp/basalt-site.ks; else : >/tmp/basalt-site.ks; fi
case "$BASALT_FINISH" in poweroff|reboot|halt) echo "$BASALT_FINISH" >/tmp/basalt-finish.ks ;; *) echo reboot >/tmp/basalt-finish.ks ;; esac

# Choices for %post (no secrets in this file).
cat >/tmp/basalt-install.env <<EOF
BASALT_ENCRYPT=$BASALT_ENCRYPT
BASALT_SHOW_RECOVERY_KEY=$BASALT_SHOW_RECOVERY_KEY
BASALT_RECOVERY_KEY_PAUSE=$BASALT_RECOVERY_KEY_PAUSE
BASALT_REPO_URL=$BASALT_REPO_URL
BASALT_UNLOCK=$BASALT_UNLOCK
BASALT_TANG_URL=$BASALT_TANG_URL
BASALT_TANG_THP=$BASALT_TANG_THP
EOF
echo "basalt: disk=$BASALT_DISK encrypt=$BASALT_ENCRYPT unlock=$BASALT_UNLOCK profile=$BASALT_PROFILE ($profile_from) lockdown=$BASALT_LOCKDOWN finish=$BASALT_FINISH"
%end

# Hand the install choices and the temporary LUKS passphrase to the chroot.
%post --nochroot --log=/mnt/sysroot/root/basalt-install-nochroot.log
#!/bin/bash
set -eu
install -m 0600 /tmp/basalt-install.env /mnt/sysroot/root/.basalt-install.env
if [ -s /tmp/basalt-luks.pass ]; then
  install -m 0600 /tmp/basalt-luks.pass /mnt/sysroot/root/.basalt-luks.pass
fi
cp /tmp/basalt-pre.log /mnt/sysroot/root/basalt-install-pre.log 2>/dev/null || :
%end

%post --log=/root/basalt-install-post.log
#!/bin/bash
# No `set -x`: this section handles key material.
set -eu
. /root/.basalt-install.env
log() { echo "basalt-post: $*"; }

# Lab or private repository URL for the installed system (default: the
# https://obpkg.org URLs basalt-release ships). Its tools repository is
# <URL>/tools, the lab layout.
if [ -n "${BASALT_REPO_URL:-}" ]; then
  echo "$BASALT_REPO_URL" >/etc/dnf/vars/basalt_repo_url
  echo "$BASALT_REPO_URL/tools" >/etc/dnf/vars/basalt_tools_url
fi

# --- boot loader: serial-first menu with a visible timeout, no splash args --
sed -i -e '/^GRUB_TERMINAL/d' -e '/^GRUB_SERIAL_COMMAND/d' -e '/^GRUB_TIMEOUT_STYLE/d' /etc/default/grub
cat >>/etc/default/grub <<'EOF'
GRUB_TIMEOUT_STYLE=menu
GRUB_TERMINAL_INPUT="serial console"
GRUB_TERMINAL_OUTPUT="serial console"
GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
EOF
sed -i -E 's/^GRUB_CMDLINE_LINUX="(.*)"/GRUB_CMDLINE_LINUX="\1"/; s/ ?rhgb//; s/ ?quiet//' /etc/default/grub
grubby --update-kernel=ALL --remove-args="rhgb quiet" || :
grub2-editenv - unset menu_auto_hide || :

# --- boot splash: Basalt theme; text prompt on the serial console --------------
if command -v plymouth-set-default-theme >/dev/null; then
  plymouth-set-default-theme basalt || :
fi

# --- disk encryption: unlock method + recovery key, installer passphrase removed --
#   tpm2       systemd-cryptenroll TPM2 key sealed to PCR 7
#   tang       Clevis bound to a Tang server (network-bound disk encryption)
#   tpm2+tang  Clevis Shamir secret sharing, threshold 2: TPM2 (PCR 7) and Tang
# The recovery key is enrolled in every mode.
if [ "$BASALT_ENCRYPT" = 1 ] && [ -s /root/.basalt-luks.pass ]; then
  dev="$(blkid -t TYPE=crypto_LUKS -o device | head -1)"
  [ -n "$dev" ] || { log "no LUKS device found"; exit 1; }
  pass=/root/.basalt-luks.pass
  tpm=0
  if [ -e /dev/tpmrm0 ] || [ -e /dev/tpm0 ]; then tpm=1; fi
  tang_cfg() {
    if [ -n "${BASALT_TANG_THP:-}" ]; then
      printf '{"url":"%s","thp":"%s"}' "$BASALT_TANG_URL" "$BASALT_TANG_THP"
    else
      printf '{"url":"%s"}' "$BASALT_TANG_URL"
    fi
  }
  # -y trusts the Tang advertisement; only without a thumbprint to check.
  trust=""
  if [ -z "${BASALT_TANG_THP:-}" ]; then trust="-y"; fi
  case "$BASALT_UNLOCK" in
    tpm2)
      if [ "$tpm" = 1 ]; then
        # PCR 7 = Secure Boot state. systemd binds no PCRs unless told to.
        systemd-cryptenroll --unlock-key-file="$pass" --tpm2-device=auto --tpm2-pcrs=7 "$dev"
        log "TPM2 key enrolled on $dev (PCR 7)"
      else
        log "WARNING: no TPM found; the recovery key is the only way to unlock $dev"
      fi ;;
    tang)
      clevis luks bind $trust -d "$dev" -k "$pass" tang "$(tang_cfg)"
      log "Clevis bound $dev to Tang $BASALT_TANG_URL" ;;
    tpm2+tang)
      [ "$tpm" = 1 ] || { log "basalt.unlock=tpm2+tang needs a TPM"; exit 1; }
      clevis luks bind $trust -d "$dev" -k "$pass" sss \
        "{\"t\":2,\"pins\":{\"tang\":[$(tang_cfg)],\"tpm2\":{\"pcr_bank\":\"sha256\",\"pcr_ids\":\"7\"}}}"
      log "Clevis bound $dev to the TPM2 (PCR 7) and Tang $BASALT_TANG_URL, both required" ;;
  esac
  if [ "$BASALT_UNLOCK" != tpm2 ] && [ -z "${BASALT_TANG_THP:-}" ]; then
    log "WARNING: Tang key trusted on first use; compare its thumbprint (clevis luks list -d $dev)"
  fi
  umask 077
  systemd-cryptenroll --unlock-key-file="$pass" --recovery-key "$dev" >/root/basalt-recovery-key.txt
  chmod 0400 /root/basalt-recovery-key.txt
  log "recovery key enrolled ($(wc -c </root/basalt-recovery-key.txt) bytes, stored in /root/basalt-recovery-key.txt)"
  # Remove the installer's passphrase by its slot number: a Clevis key slot
  # also counts as a "password" slot for systemd-cryptenroll. Each slot is
  # tested on its own with token plugins off; otherwise cryptsetup unlocks
  # through the TPM2 token first and names the TPM2 slot.
  slot=""
  for n in $(cryptsetup luksDump "$dev" | awk '/^Keyslots:/ {k = 1; next} /^[A-Z]/ {k = 0} k && /^  [0-9]+: / {sub(":", "", $1); print $1}'); do
    if cryptsetup open --test-passphrase --disable-external-tokens --key-slot "$n" --key-file "$pass" "$dev" 2>/dev/null; then
      slot="$n"; break
    fi
  done
  [ -n "$slot" ] || { log "could not find the installer passphrase slot"; exit 1; }
  systemd-cryptenroll --unlock-key-file="$pass" --wipe-slot="$slot" "$dev"
  log "installer passphrase (key slot $slot) removed"
  shred -u "$pass"

  # Unattended unlock: systemd's TPM2 token (tpm2), or Clevis in the
  # initramfs answering the passphrase prompt (tang, tpm2+tang). Never
  # headless, so the recovery key can be typed on the console when the
  # unlock fails.
  tpm_opt=0
  if [ "$BASALT_UNLOCK" = tpm2 ] && [ "$tpm" = 1 ]; then tpm_opt=1; fi
  awk -v tpm="$tpm_opt" 'BEGIN{OFS=" "} /^[[:space:]]*#/ || NF < 3 {print; next}
       { o = (NF >= 4 ? $4 : "none"); if (o == "none" || o == "-") o = "";
         n = split(o, a, ","); out = "";
         for (i = 1; i <= n; i++) if (a[i] != "headless=true" && a[i] !~ /^tpm2-device=/) out = out (out == "" ? "" : ",") a[i];
         if (tpm) out = out (out == "" ? "" : ",") "tpm2-device=auto";
         if (out == "") out = "none";
         print $1, $2, ($3 == "" ? "none" : $3), out }' /etc/crypttab >/etc/crypttab.new
  cat /etc/crypttab.new >/etc/crypttab && rm -f /etc/crypttab.new

  mkdir -p /etc/motd.d
  cat >/etc/motd.d/basalt-recovery-key <<'EOF'
Basalt OS: the disk recovery key is in /root/basalt-recovery-key.txt.
Store it somewhere safe, off this machine, then delete the file and this
notice (rm /root/basalt-recovery-key.txt /etc/motd.d/basalt-recovery-key).
EOF
  if [ "${BASALT_SHOW_RECOVERY_KEY:-1}" = 1 ]; then
    { echo; echo "Basalt OS disk recovery key (store it safely, it is shown once):";
      cat /root/basalt-recovery-key.txt; echo; } >/dev/console 2>/dev/null || :
    sleep "${BASALT_RECOVERY_KEY_PAUSE:-30}"
  fi
fi
rm -f /root/.basalt-install.env

# Initramfs with the unlock support (TPM2 or Clevis and network), the
# crypttab above and the theme.
dracut -f --regenerate-all

# --- snapshots: snapper config, default subvolume, GRUB snapshot menu ----------
# Also writes grub.cfg (with the theme and snapshot hooks), so it runs last.
# No snapshot here: files written by the installer are only labeled at the end
# of the install, and first-boot setup has not run. The first snapshot is
# taken on the first boot (basalt-initial-snapshot.service).
basalt-snapshots-setup --no-initial-snapshot

restorecon -R /etc /root /boot /var/log 2>/dev/null || :
log "done"
%end
