# Basalt OS server kickstart (Fedora 44 base, Anaconda).
#
# Embedded into the Fedora netinst ISO by scripts/iso.sh (mkksiso). Installs a
# minimal server from the Fedora mirrors plus the Basalt OS packages, which
# travel on the ISO itself (/basalt on the media).
#
# Storage, encryption, accounts and the end of the install are generated in
# %pre from two optional sources:
#   - kernel arguments (edit the boot entry):
#       basalt.encrypt=0      plain btrfs, no LUKS2 (default: 1, encrypted)
#       basalt.disk=vda       target disk (default: the first fixed disk)
#       basalt.finish=poweroff|reboot   (default: reboot)
#   - a site file on the media, /basalt/site.conf (same names, shell syntax:
#     BASALT_ENCRYPT, BASALT_DISK, BASALT_FINISH, BASALT_SHOW_RECOVERY_KEY,
#     BASALT_RECOVERY_KEY_PAUSE, BASALT_REPO_URL) and /basalt/site.ks (accounts: sshkey, user, rootpw).
#     Without site.ks the installer asks for a root password or a user.
#
# Layout (ADR "update model"): GPT, ESP, /boot (ext4), and one btrfs file
# system, on LUKS2 unless disabled, with these subvolumes:
#   root            /                   the system; snapshots and rollback apply here
#   home            /home               user data, never rolled back
#   srv             /srv                served data
#   var_log         /var/log            logs survive a rollback (and explain it)
#   var_cache       /var/cache          caches, not worth snapshotting
#   var_tmp         /var/tmp
#   var_spool       /var/spool          mail and print queues
#   var_lib_containers  /var/lib/containers   container images and volumes
#   var_lib_libvirt     /var/lib/libvirt      virtual machines
#   var_lib_pgsql       /var/lib/pgsql        PostgreSQL
#   var_lib_mysql       /var/lib/mysql        MariaDB / MySQL
#   root/.snapshots /.snapshots         snapper (created by basalt-snapshots-setup)
# /opt stays in the root: packages install there too, and it must roll back
# with the package database. The rest of /var/lib (SELinux policy store,
# alternatives, systemd state) also stays with the root for the same reason.
# compress=zstd:1 is Anaconda's default for btrfs on Fedora and is active
# while the system is written.

text
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --utc
network --bootproto=dhcp --device=link --activate --onboot=on --hostname=basalt
selinux --enforcing
# The firewall comes from basalt-release-server (zone "basalt", SSH only).
firewall --use-system-defaults
services --enabled=sshd,firewalld,auditd,basalt-snapshot-boot,basalt-initial-snapshot,basalt-grub-theme
skipx
firstboot --disable
bootloader --timeout=5 --append="console=tty0 console=ttyS0,115200n8"

# Fedora package repositories ($releasever is the installer's release).
url --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-$releasever&arch=$basearch"
repo --name=updates --mirrorlist="https://mirrors.fedoraproject.org/mirrorlist?repo=updates-released-f$releasever&arch=$basearch"

# Generated by %pre: Basalt repository, storage, accounts, end action.
%include /tmp/basalt-repo.ks
%include /tmp/basalt-storage.ks
%include /tmp/basalt-site.ks
%include /tmp/basalt-finish.ks

%pre --log=/tmp/basalt-pre.log
#!/bin/bash
set -eu
media=/run/install/repo/basalt
BASALT_ENCRYPT=1
BASALT_DISK=
BASALT_FINISH=reboot
BASALT_SHOW_RECOVERY_KEY=1
BASALT_RECOVERY_KEY_PAUSE=30
BASALT_REPO_URL=
if [ -r "$media/site.conf" ]; then . "$media/site.conf"; fi
for arg in $(cat /proc/cmdline); do
  case "$arg" in
    basalt.encrypt=*) BASALT_ENCRYPT="${arg#*=}" ;;
    basalt.disk=*) BASALT_DISK="${arg#*=}" ;;
    basalt.finish=*) BASALT_FINISH="${arg#*=}" ;;
  esac
done

# Basalt OS packages: from the media when present, else from BASALT_REPO_URL.
if [ -d "$media/repo" ]; then
  echo "repo --name=basalt --baseurl=file://$media/repo/\$releasever/\$basearch/" >/tmp/basalt-repo.ks
elif [ -n "$BASALT_REPO_URL" ]; then
  echo "repo --name=basalt --baseurl=$BASALT_REPO_URL/\$releasever/\$basearch/" >/tmp/basalt-repo.ks
else
  echo "Basalt OS packages not found on the media and BASALT_REPO_URL is not set" >&2
  exit 1
fi

# Target disk: the first fixed, writable disk unless one is given.
if [ -z "$BASALT_DISK" ]; then
  BASALT_DISK="$(lsblk -dnpo NAME,TYPE,RM,RO | awk '$2 == "disk" && $3 == 0 && $4 == 0 && $1 !~ /\/(zram|loop|nbd|ram)[0-9]/ {print $1; exit}')"
fi
BASALT_DISK="${BASALT_DISK#/dev/}"
[ -n "$BASALT_DISK" ] || { echo "no target disk" >&2; exit 1; }

luks=""
if [ "$BASALT_ENCRYPT" = 1 ]; then
  # A random passphrase that only lives in the installer's memory. %post
  # adds the TPM2 key and the recovery key, then removes this passphrase.
  umask 077
  tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48 >/tmp/basalt-luks.pass
  luks="--encrypted --luks-version=luks2 --passphrase=$(cat /tmp/basalt-luks.pass)"
fi

cat >/tmp/basalt-storage.ks <<EOF
ignoredisk --only-use=$BASALT_DISK
zerombr
clearpart --all --initlabel --drives=$BASALT_DISK --disklabel=gpt
part /boot/efi --fstype=efi --size=600 --ondisk=$BASALT_DISK
part /boot --fstype=ext4 --size=1024 --ondisk=$BASALT_DISK
part btrfs.basalt --size=8192 --grow --ondisk=$BASALT_DISK $luks
btrfs none --label=basalt btrfs.basalt
btrfs / --subvol --name=root LABEL=basalt
btrfs /home --subvol --name=home LABEL=basalt
btrfs /srv --subvol --name=srv LABEL=basalt
btrfs /var/log --subvol --name=var_log LABEL=basalt
btrfs /var/cache --subvol --name=var_cache LABEL=basalt
btrfs /var/tmp --subvol --name=var_tmp LABEL=basalt
btrfs /var/spool --subvol --name=var_spool LABEL=basalt
btrfs /var/lib/containers --subvol --name=var_lib_containers LABEL=basalt
btrfs /var/lib/libvirt --subvol --name=var_lib_libvirt LABEL=basalt
btrfs /var/lib/pgsql --subvol --name=var_lib_pgsql LABEL=basalt
btrfs /var/lib/mysql --subvol --name=var_lib_mysql LABEL=basalt
EOF

if [ -r "$media/site.ks" ]; then cp "$media/site.ks" /tmp/basalt-site.ks; else : >/tmp/basalt-site.ks; fi
case "$BASALT_FINISH" in poweroff|reboot|halt) echo "$BASALT_FINISH" >/tmp/basalt-finish.ks ;; *) echo reboot >/tmp/basalt-finish.ks ;; esac

# Choices for %post (no secrets in this file).
cat >/tmp/basalt-install.env <<EOF
BASALT_ENCRYPT=$BASALT_ENCRYPT
BASALT_SHOW_RECOVERY_KEY=$BASALT_SHOW_RECOVERY_KEY
BASALT_RECOVERY_KEY_PAUSE=$BASALT_RECOVERY_KEY_PAUSE
BASALT_REPO_URL=$BASALT_REPO_URL
EOF
echo "basalt: disk=$BASALT_DISK encrypt=$BASALT_ENCRYPT finish=$BASALT_FINISH"
%end

%packages
@core
basalt-release
basalt-release-server
basalt-logos
basalt-logos-httpd
basalt-grub2-theme
plymouth-theme-basalt
basalt-snapshots
-fedora-release
-fedora-release-common
-fedora-release-identity-basic
-fedora-logos
-fedora-logos-httpd
-generic-release
-generic-logos
btrfs-progs
cryptsetup
tpm2-tss
tpm2-tools
mokutil
efibootmgr
audit
policycoreutils-python-utils
setools-console
compsize
glibc-langpack-en
snapper
libdnf5-plugin-actions
%end

# Hand the install choices and the temporary LUKS passphrase to the chroot.
%post --nochroot --log=/mnt/sysroot/root/basalt-install-nochroot.log
#!/bin/bash
set -eu
install -m 0600 /tmp/basalt-install.env /mnt/sysroot/root/.basalt-install.env
if [ -s /tmp/basalt-luks.pass ]; then
  install -m 0600 /tmp/basalt-luks.pass /mnt/sysroot/root/.basalt-luks.pass
fi
cp /tmp/basalt-pre.log /mnt/sysroot/root/basalt-install-pre.log 2>/dev/null || :
%end

%post --log=/root/basalt-install-post.log
#!/bin/bash
# No `set -x`: this section handles key material.
set -eu
. /root/.basalt-install.env
log() { echo "basalt-post: $*"; }

# Lab or private repository URL for the installed system.
if [ -n "${BASALT_REPO_URL:-}" ]; then
  echo "$BASALT_REPO_URL" >/etc/dnf/vars/basalt_repo_url
fi

# --- boot loader: serial-first menu with a visible timeout, no splash args --
sed -i -e '/^GRUB_TERMINAL/d' -e '/^GRUB_SERIAL_COMMAND/d' -e '/^GRUB_TIMEOUT_STYLE/d' /etc/default/grub
cat >>/etc/default/grub <<'EOF'
GRUB_TIMEOUT_STYLE=menu
GRUB_TERMINAL_INPUT="serial console"
GRUB_TERMINAL_OUTPUT="serial console"
GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
EOF
sed -i -E 's/^GRUB_CMDLINE_LINUX="(.*)"/GRUB_CMDLINE_LINUX="\1"/; s/ ?rhgb//; s/ ?quiet//' /etc/default/grub
grubby --update-kernel=ALL --remove-args="rhgb quiet" || :
grub2-editenv - unset menu_auto_hide || :

# --- boot splash: Basalt theme; text prompt on the serial console --------------
if command -v plymouth-set-default-theme >/dev/null; then
  plymouth-set-default-theme basalt || :
fi

# --- disk encryption: TPM2 (PCR 7) + recovery key, installer passphrase removed --
if [ "$BASALT_ENCRYPT" = 1 ] && [ -s /root/.basalt-luks.pass ]; then
  dev="$(blkid -t TYPE=crypto_LUKS -o device | head -1)"
  [ -n "$dev" ] || { log "no LUKS device found"; exit 1; }
  pass=/root/.basalt-luks.pass
  if [ -e /dev/tpmrm0 ] || [ -e /dev/tpm0 ]; then
    # PCR 7 = Secure Boot state. systemd binds no PCRs unless told to.
    systemd-cryptenroll --unlock-key-file="$pass" --tpm2-device=auto --tpm2-pcrs=7 "$dev"
    log "TPM2 key enrolled on $dev (PCR 7)"
    tpm=1
  else
    log "WARNING: no TPM found; the recovery key is the only way to unlock $dev"
    tpm=0
  fi
  umask 077
  systemd-cryptenroll --unlock-key-file="$pass" --recovery-key "$dev" >/root/basalt-recovery-key.txt
  chmod 0400 /root/basalt-recovery-key.txt
  log "recovery key enrolled ($(wc -c </root/basalt-recovery-key.txt) bytes, stored in /root/basalt-recovery-key.txt)"
  systemd-cryptenroll --unlock-key-file="$pass" --wipe-slot=password "$dev"
  log "installer passphrase removed"
  shred -u "$pass"

  # Unattended unlock through the TPM, with a prompt (not headless) when the
  # TPM refuses, so the recovery key can be typed on the console.
  if [ "$tpm" = 1 ]; then
    awk 'BEGIN{OFS=" "} /^[[:space:]]*#/ || NF < 3 {print; next}
         { o = (NF >= 4 ? $4 : "none"); if (o == "none" || o == "-") o = "";
           n = split(o, a, ","); out = "";
           for (i = 1; i <= n; i++) if (a[i] != "headless=true" && a[i] !~ /^tpm2-device=/) out = out (out == "" ? "" : ",") a[i];
           out = out (out == "" ? "" : ",") "tpm2-device=auto";
           print $1, $2, ($3 == "" ? "none" : $3), out }' /etc/crypttab >/etc/crypttab.new
    cat /etc/crypttab.new >/etc/crypttab && rm -f /etc/crypttab.new
  fi

  mkdir -p /etc/motd.d
  cat >/etc/motd.d/basalt-recovery-key <<'EOF'
Basalt OS: the disk recovery key is in /root/basalt-recovery-key.txt.
Store it somewhere safe, off this machine, then delete the file and this
notice (rm /root/basalt-recovery-key.txt /etc/motd.d/basalt-recovery-key).
EOF
  if [ "${BASALT_SHOW_RECOVERY_KEY:-1}" = 1 ]; then
    { echo; echo "Basalt OS disk recovery key (store it safely, it is shown once):";
      cat /root/basalt-recovery-key.txt; echo; } >/dev/console 2>/dev/null || :
    sleep "${BASALT_RECOVERY_KEY_PAUSE:-30}"
  fi
fi
rm -f /root/.basalt-install.env

# Initramfs with the TPM2 unlock support, the crypttab above and the theme.
dracut -f --regenerate-all

# --- snapshots: snapper config, default subvolume, GRUB snapshot menu ----------
# Also writes grub.cfg (with the theme and snapshot hooks), so it runs last.
# No snapshot here: files written by the installer are only labeled at the end
# of the install, and first-boot setup has not run. The first snapshot is
# taken on the first boot (basalt-initial-snapshot.service).
basalt-snapshots-setup --no-initial-snapshot

restorecon -R /etc /root /boot /var/log 2>/dev/null || :
log "done"
%end
