package i18n

import (
	"encoding/binary"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// go test ./internal/i18n -update rewrites po/basalt-assistant.pot from
// the T and N calls in the sources.
var update = flag.Bool("update", false, "rewrite the catalog template")

const (
	pkgRoot  = "../.."
	potPath  = "../../po/basalt-assistant.pot"
	poGlob   = "../../po/*.po"
	potHeadr = `# Translation template of basalt-assistant (the basalt command).
# Generated by: go test ./internal/i18n -update
# The msgid is the English reference text.
msgid ""
msgstr ""
"Project-Id-Version: basalt-assistant\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
`
)

type msg struct {
	id, plural string
	refs       []string
}

// extract finds every i18n.T("...") and i18n.N("...", "...", n) call.
func extract(t *testing.T) []*msg {
	t.Helper()
	byID := map[string]*msg{}
	fset := token.NewFileSet()
	err := filepath.WalkDir(pkgRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() && (d.Name() == "testdata" || d.Name() == "third_party") {
			return filepath.SkipDir
		}
		if d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		f, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return err
		}
		ast.Inspect(f, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			x, ok := sel.X.(*ast.Ident)
			if !ok || x.Name != "i18n" || (sel.Sel.Name != "T" && sel.Sel.Name != "N") {
				return true
			}
			lit := func(i int) string {
				if i >= len(call.Args) {
					t.Errorf("%s: i18n.%s needs a literal string", fset.Position(call.Pos()), sel.Sel.Name)
					return ""
				}
				b, ok := call.Args[i].(*ast.BasicLit)
				if !ok || b.Kind != token.STRING {
					t.Errorf("%s: i18n.%s needs a literal string, not an expression", fset.Position(call.Pos()), sel.Sel.Name)
					return ""
				}
				s, _ := strconv.Unquote(b.Value)
				return s
			}
			m := &msg{id: lit(0)}
			if sel.Sel.Name == "N" {
				m.plural = lit(1)
			}
			pos := fset.Position(call.Pos())
			rel, _ := filepath.Rel(pkgRoot, pos.Filename)
			if old := byID[m.id]; old != nil {
				m = old
			} else {
				byID[m.id] = m
			}
			m.refs = append(m.refs, fmt.Sprintf("%s:%d", rel, pos.Line))
			return true
		})
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	var out []*msg
	for _, m := range byID {
		out = append(out, m)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].refs[0] < out[j].refs[0] })
	return out
}

// poQuote writes a string as a PO string (one line; \n escaped).
func poQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`)
	return `"` + r.Replace(s) + `"`
}

func renderPOT(ms []*msg) string {
	var b strings.Builder
	b.WriteString(potHeadr)
	for _, m := range ms {
		b.WriteString("\n#: " + strings.Join(m.refs, " ") + "\n")
		if strings.Contains(m.id, "%") {
			b.WriteString("#, c-format\n")
		}
		b.WriteString("msgid " + poQuote(m.id) + "\n")
		if m.plural != "" {
			b.WriteString("msgid_plural " + poQuote(m.plural) + "\nmsgstr[0] \"\"\nmsgstr[1] \"\"\n")
		} else {
			b.WriteString("msgstr \"\"\n")
		}
	}
	return b.String()
}

func TestCatalogTemplateIsCurrent(t *testing.T) {
	ms := extract(t)
	if len(ms) == 0 {
		t.Fatal("no translatable strings found")
	}
	want := renderPOT(ms)
	if *update {
		if err := os.WriteFile(potPath, []byte(want), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(potPath)
	if err != nil || string(got) != want {
		t.Fatalf("po/basalt-assistant.pot is not current: run go test ./internal/i18n -update and translate the new strings")
	}
}

// poEntry is one parsed PO message.
type poEntry struct {
	id, plural string
	strs       []string
	fuzzy      bool
}

func parsePO(t *testing.T, path string) (header string, entries map[string]*poEntry) {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	entries = map[string]*poEntry{}
	var cur *poEntry
	var target *string
	flush := func() {
		if cur == nil {
			return
		}
		if cur.id == "" {
			if len(cur.strs) > 0 {
				header = cur.strs[0]
			}
		} else {
			entries[cur.id] = cur
		}
		cur, target = nil, nil
	}
	fuzzy := false
	unq := func(s string) string {
		v, err := strconv.Unquote(strings.TrimSpace(s))
		if err != nil {
			t.Fatalf("%s: bad string %s", path, s)
		}
		return v
	}
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)
		switch {
		case line == "":
			flush()
		case strings.HasPrefix(line, "#,"):
			fuzzy = strings.Contains(line, "fuzzy")
		case strings.HasPrefix(line, "#"):
		case strings.HasPrefix(line, "msgid_plural "):
			cur.plural = unq(line[len("msgid_plural "):])
			target = &cur.plural
		case strings.HasPrefix(line, "msgid "):
			flush()
			cur = &poEntry{id: unq(line[len("msgid "):]), fuzzy: fuzzy}
			fuzzy = false
			target = &cur.id
		case strings.HasPrefix(line, "msgstr"):
			_, v, _ := strings.Cut(line, " ")
			cur.strs = append(cur.strs, unq(v))
			target = &cur.strs[len(cur.strs)-1]
		case strings.HasPrefix(line, `"`):
			*target += unq(line)
		}
	}
	flush()
	return header, entries
}

var reVerb = regexp.MustCompile(`%[-+# 0]*[0-9]*(?:\.[0-9]+)?[a-zA-Z%]`)

func verbs(s string) string { return strings.Join(reVerb.FindAllString(s, -1), " ") }

func TestTranslationsAreComplete(t *testing.T) {
	ms := extract(t)
	files, _ := filepath.Glob(poGlob)
	if len(files) == 0 {
		t.Fatal("no translations in po/")
	}
	for _, f := range files {
		header, entries := parsePO(t, f)
		if !strings.Contains(header, "Plural-Forms:") || !strings.Contains(header, "charset=UTF-8") {
			t.Errorf("%s: the header needs Plural-Forms and charset=UTF-8", f)
		}
		for _, m := range ms {
			e := entries[m.id]
			if e == nil {
				t.Errorf("%s: missing %q", f, m.id)
				continue
			}
			if e.fuzzy {
				t.Errorf("%s: fuzzy %q", f, m.id)
			}
			for i, s := range e.strs {
				if s == "" {
					t.Errorf("%s: empty translation %d of %q", f, i, m.id)
				}
				if verbs(s) != verbs(m.id) && (m.plural == "" || verbs(s) != verbs(m.plural)) {
					t.Errorf("%s: placeholders of %q differ: %q", f, m.id, s)
				}
			}
			if m.plural != "" && len(e.strs) < 2 {
				t.Errorf("%s: %q needs its plural forms", f, m.id)
			}
		}
		for id := range entries {
			found := false
			for _, m := range ms {
				found = found || m.id == id
			}
			if !found {
				t.Errorf("%s: obsolete entry %q (remove it)", f, id)
			}
		}
	}
}

// writeMO compiles PO entries into a little-endian .mo file, like msgfmt.
func writeMO(header string, entries map[string]*poEntry) []byte {
	type pair struct{ k, v string }
	pairs := []pair{{"", header}}
	for _, e := range entries {
		k := e.id
		if e.plural != "" {
			k += "\x00" + e.plural
		}
		pairs = append(pairs, pair{k, strings.Join(e.strs, "\x00")})
	}
	sort.Slice(pairs, func(i, j int) bool { return pairs[i].k < pairs[j].k })
	n := len(pairs)
	origT, transT := 28, 28+8*n
	b := make([]byte, transT+8*n)
	le := binary.LittleEndian
	le.PutUint32(b[0:], 0x950412de)
	le.PutUint32(b[8:], uint32(n))
	le.PutUint32(b[12:], uint32(origT))
	le.PutUint32(b[16:], uint32(transT))
	for i, p := range pairs {
		for j, s := range []string{p.k, p.v} {
			table := origT
			if j == 1 {
				table = transT
			}
			le.PutUint32(b[table+8*i:], uint32(len(s)))
			le.PutUint32(b[table+8*i+4:], uint32(len(b)))
			b = append(b, append([]byte(s), 0)...)
		}
	}
	return b
}

func TestBrazilianPortugueseCatalog(t *testing.T) {
	header, entries := parsePO(t, "../../po/pt_BR.po")
	dir := t.TempDir()
	p := filepath.Join(dir, "pt_BR", "LC_MESSAGES")
	if err := os.MkdirAll(p, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(p, Domain+".mo"), writeMO(header, entries), 0o644); err != nil {
		t.Fatal(err)
	}
	old := LocaleDir
	LocaleDir = dir
	t.Cleanup(func() { LocaleDir = old; Reset() })
	t.Setenv("LANGUAGE", "")
	t.Setenv("LC_ALL", "pt_BR.UTF-8")
	Reset()
	if Lang() != "pt_BR" {
		t.Fatalf("language %q", Lang())
	}
	if got := T("Nothing was sent."); got != "Nada foi enviado." {
		t.Fatalf("T: %q", got)
	}
	one := "%d value was changed to hide personal data (shown as [redacted])."
	many := "%d values were changed to hide personal data (shown as [redacted])."
	// pt_BR: one for 0 and 1 (plural=(n > 1)).
	if N(one, many, 0) != entries[one].strs[0] || N(one, many, 1) != entries[one].strs[0] || N(one, many, 2) != entries[one].strs[1] {
		t.Fatalf("plural forms: %q %q", N(one, many, 1), N(one, many, 2))
	}
	if T("not in the catalog") != "not in the catalog" {
		t.Fatal("unknown text must stay the reference text")
	}
}

func TestReferenceLanguage(t *testing.T) {
	old := LocaleDir
	LocaleDir = t.TempDir()
	t.Cleanup(func() { LocaleDir = old; Reset() })
	for _, env := range []string{"C", "en_US.UTF-8", "POSIX"} {
		t.Setenv("LANGUAGE", "")
		t.Setenv("LC_ALL", env)
		Reset()
		if T("Nothing was sent.") != "Nothing was sent." || Lang() != "" {
			t.Fatalf("%s: %q %q", env, T("Nothing was sent."), Lang())
		}
		if N("%d file", "%d files", 1) != "%d file" || N("%d file", "%d files", 0) != "%d files" {
			t.Fatal("English plural rule")
		}
	}
}

func TestLanguages(t *testing.T) {
	t.Setenv("LANGUAGE", "pt_BR:fr")
	t.Setenv("LC_ALL", "")
	t.Setenv("LC_MESSAGES", "")
	t.Setenv("LANG", "de_DE.UTF-8@euro")
	if got := strings.Join(Languages(), " "); got != "pt_BR pt fr de_DE de" {
		t.Fatal(got)
	}
}

func TestParseMORejectsGarbage(t *testing.T) {
	for _, b := range [][]byte{nil, []byte("short"), make([]byte, 40)} {
		if _, err := ParseMO(b); err == nil {
			t.Fatalf("accepted %q", b)
		}
	}
}
